version: '3'

services:
  api:
    image: api
    build:
      context: .
      dockerfile: Api/Dockerfile



  webmvc:
    image: webmvc
    build:
      context: .
      dockerfile: WebMVC/Dockerfile

