version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout

      # test
      - run: |
         docker-compose -f docker-compose.unittests.yml run --rm unittests
         

      # build image
      - run: |
         docker info
         docker build -t aspnetapiapp Api
         docker build -t aspnetwebapp WebMVC

      # deploy the image
      - run: |
         docker login --username=$HEROKU_USERNAME --password=$HEROKU_API_KEY registry.heroku.com
         docker tag aspnetapiapp registry.heroku.com/$HEROKU_API_NAME/web
         docker push registry.heroku.com/$HEROKU_API_NAME/web  
         docker tag aspnetwebapp registry.heroku.com/$HEROKU_WEB_NAME/web
         docker push registry.heroku.com/$HEROKU_WEB_NAME/web